### PR TITLE
Set snackbar children under the text portion of the component

### PR DESCRIPTION
**Pull request by impronunciable**

### CODE REVIEW

**Comment by developit** [comment]
Good catch! I'm going to give you contrib rights here actually.

**Comment by impronunciable** [comment]
thx!

**Comment by impronunciable** [comment]
@developit can I ask you for a npm publish?

**Comment by developit** [comment]
yep, [just did](https://github.com/developit/preact-mdl/releases/tag/1.3.1)! 😊

**Comment by impronunciable** [comment]
thanks!

**Comment by TheNeikos** [comment]
Why exactly was this added?

The [website states that one shouldn't put anything](https://getmdl.io/components/index.html#snackbar-section) into the `text` div.

**Comment by developit** [comment]
@TheNeikos I think it's for those using `<Snackbar />` declaratively instead of via the imperative API? Not sure.  I use the imperative API via a ref ([example here](https://jsfiddle.net/developit/Lmvwv4zx/)).

**Comment by TheNeikos** [comment]
I see, thank you!

**Pull request merged**
