### PR TITLE
Add examples for Icon, Button, Card, and Layout

### PR DESCRIPTION
**Pull request by brenapp**
Just some examples in components that I know

### CODE REVIEW

**Comment by developit** [comment]
We'll have to migrate these into the Docblock comments, `docs.md` is an auto-generated file and they'll get overwritten during builds.

**Comment by brenapp** [comment]
Crap, did I not add the main file in my commit! D'oh! I'm on mobile now,
but it update the pull when I get hone

**Comment by brenapp** [comment]
I added the correct commit, but it also changed the [`docs.md`](https://github.com/developit/preact-mdl/blob/master/docs.md) file when I regened the

**Comment by developit** [comment]
hehhhhh

**Pull request merged**
