### PR TITLE
Proxying open and close in Dialog to base component

### PR DESCRIPTION
**Pull request by prateekbh**
Proxying open and close in base component.
One more thing, are the .ts changes done from js file or they have to be done manually?

### CODE REVIEW

**Review by developit — COMMENTED** [review]
Think it's worth also allowing `.show()` and `.showModal()` to match the dialog spec?

**Comment by developit** [comment]
Yup, TS is derived.

**Comment by prateekbh** [comment]
@developit, done :)

**Comment by prateekbh** [comment]
@developit, do you thinks access to this.base.open via a proxy makes sense?
I guess only show, showModal and close should suffice.
Let me know what you think

**Comment by developit** [comment]
@prateekbh I had forgotten `open` was a getter.  Maybe we emulate?

```js
get open() {
  return this.base.open;
}
```

**Comment by prateekbh** [comment]
@developit i am unable to see a potential usecase for `open`.
Shall we wait for someone or ourselves to stumble upon one, and till the time go ahead with show, showModal and close only?

**Comment by developit** [comment]
Yeah I'm totally fine with that.  Worst case they could just use `.base.open`.  Good call.

**Comment by prateekbh** [comment]
@developit cool, so Good to go?

**Comment by prateekbh** [comment]
@developit lemme know if u need any further changes

**Comment by developit** [comment]
Nope, all good to merge - I was just away.

**Pull request merged**
